#import "../../fragments/Message.gql"

query roomMessage($roomGetMessageInput: RoomGetMessageInput!) {
  roomMessage(roomGetMessageInput: $roomGetMessageInput) {
    result
    message
    value {
      messages {
        ...messageField
      }
      moreAvailable
      pageAvailable
    }
  }
}
